import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { CategorySidebar } from "@/components/CategorySidebar";
import { ToolCard } from "@/components/ToolCard";
import { Button } from "@/components/ui/button";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Plus } from "lucide-react";

const tools = [
  {
    name: "Beardless Filter",
    description: "Beardless Filter: See How You Shave-no beard filter",
    logo: "🧔",
    badge: undefined,
  },
  {
    name: "Publish Markdown",
    description: "Free markdown online editor and viewer! Edit markdown online, preview in real-time, and...",
    logo: "M",
    badge: "New" as const,
  },
  {
    name: "Remove Watermark Sora 2",
    description: "Remove watermarks from Sora 2 videos in just 5 seconds. High-quality, fast, and affordable -...",
    logo: "🍌",
  },
  {
    name: "StackMention",
    description: "Explore 1000+ Tools in Multiple Categories & Niches",
    logo: "📚",
  },
  {
    name: "ReportsMate",
    description: "Transform complex marketing data into intelligent and readable reports automatically...",
    logo: "R",
  },
  {
    name: "AI Describe Music",
    description: "Instantly analyze any music, audio, or voice file with our advanced AI. Generate detailed...",
    logo: "🎵",
  },
  {
    name: "Nurturing Mail",
    description: "Email automation for directory owners. Scrape ProductHunt, automate outreach, and grow yo...",
    logo: "M",
  },
  {
    name: "NextCard",
    description: "Discover the best credit cards for your needs with our comprehensive reviews, guides, and...",
    logo: "🎴",
  },
  {
    name: "AI pet portrait generator",
    description: "AI Pet Portrait Generator is a website that provides ai pet portrait generator for loyal pe...",
    logo: "🐕",
  },
  {
    name: "Remove text from image",
    description: "Our Tool provides text removal services, offering efficient text from image, text remover from...",
    logo: "📝",
  },
  {
    name: "Beard Remover",
    description: "Beardremover.com is a professional online beard remover site, offering a powerful beard remov...",
    logo: "🪒",
  },
  {
    name: "SocLeads",
    description: "► SocLeads: best email scraper online. 🔥 Scrape emails from Google Maps, IG, FB...",
    logo: "📧",
  },
  {
    name: "4 Fashion AI",
    description: "Design outfits, run virtual try-on, create AI fashion models, build branding assets, and...",
    logo: "4",
    badge: "Deal" as const,
  },
  {
    name: "Temp Mail To",
    description: "Temp Mail To offers free disposable temporary email addresses to protect your privacy. Stay...",
    logo: "✉️",
  },
  {
    name: "Oreplot",
    description: "Oreplot is a global marketplace to buy and sell land plots with valuable mineral reserves...",
    logo: "⛏️",
  },
  {
    name: "APIGate",
    description: "Generated by APIGate",
    logo: "🚪",
  },
  {
    name: "Komentiq",
    description: "Komentiq helps teams collaborate on design reviews with powerful annotation...",
    logo: "K",
  },
  {
    name: "RichlyAI",
    description: "RichlyAI Hub is an artificial intelligence platform designed to empower creativity by g...",
    logo: "🤖",
  },
  {
    name: "Solafast",
    description: "Create, promote, and grow your token project on Solana with zero coding skills. Join the Web...",
    logo: "⚡",
  },
  {
    name: "VCDir",
    description: "Comprehensive database of venture capital firms worldwide. Find VCs by country,...",
    logo: "💼",
  },
  {
    name: "Mr Fraud Checker",
    description: "Instantly verify phone numbers and reduce parcel fraud. Onecodeshop Fraud Checker helps...",
    logo: "🕵️",
  },
  {
    name: "PrintOnDemandBusiness.com",
    description: "Find and filter print-on-demand suppliers based on products, regions served, facility locations,...",
    logo: "🖨️",
    badge: "Deal" as const,
  },
  {
    name: "nano banana",
    description: "nano banana is a free AI image editor that lets you generate and edit images with natural...",
    logo: "N",
  },
  {
    name: "Sidekick",
    description: "All in one AI Workspace with unlimited connections",
    logo: "💜",
  },
  {
    name: "Psy Planner",
    description: "Stay organized, save time, and deliver better care with Psy Planner. Manage clients, sessions...",
    logo: "P",
  },
  {
    name: "SupaRedd",
    description: "Reddit Marketing with Human-like AI",
    logo: "🔴",
  },
  {
    name: "BestColorPages",
    description: "Discover hundreds of free printable coloring pages for kids and adults. Download instantly!",
    logo: "🎨",
  },
  {
    name: "CustoQ",
    description: "Boost conversions with AI helpdesks that deliver clarity and stay up to date automatically throu...",
    logo: "🟠",
  },
  {
    name: "AI Architectures",
    description: "Generate professional architectural plans, renderings, and designs with our advanced AI...",
    logo: "🏛️",
  },
  {
    name: "UrTempMail",
    description: "Get free, instant temporary email addresses. And protect your privacy.",
    logo: "📬",
  },
  {
    name: "Toolfio",
    description: "Find the best tools for you. Discover curated tools, resources, and platforms for makers,...",
    logo: "⚙️",
  },
  {
    name: "Pet Food Wizard",
    description: "Scan or upload a pet food barcode to instantly check its quality. Get detailed nutrition and...",
    logo: "🐾",
  },
  {
    name: "Sidecrate",
    description: "Buy and sell developer side projects, code, and digital products. Find prototypes, MVPs, and...",
    logo: "📦",
  },
  {
    name: "Clean Audio",
    description: "Remove background noise, filler words, and awkward silences from your audio automaticall...",
    logo: "🎧",
  },
  {
    name: "Odin",
    description: "Turn your big goals into daily momentum",
    logo: "⬛",
  },
  {
    name: "DESI Founder",
    description: "Community Platform for Startups and Entrepreneurs, where you can Build, Connect,...",
    logo: "📱",
  },
];

const Index = () => {
  const [tools, setTools] = useState<any[]>([]);
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    checkAuth();
    fetchTools();
  }, []);

  const checkAuth = async () => {
    const { data: { session } } = await supabase.auth.getSession();
    setUser(session?.user ?? null);
  };

  const fetchTools = async () => {
    const { data, error } = await supabase
      .from("tools")
      .select("*")
      .order("created_at", { ascending: false });

    if (!error && data) {
      setTools(data);
    }
    setLoading(false);
  };

  return (
    <SidebarProvider>
      <div className="flex min-h-screen w-full bg-background">
        <CategorySidebar />
        
        <main className="flex-1 w-full">
          <header className="border-b border-border bg-card sticky top-0 z-10">
            <div className="container mx-auto px-6 py-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <SidebarTrigger className="lg:hidden" />
                  <div className="bg-foreground text-background px-2.5 py-1 rounded font-bold text-xs">
                    FINDLY.TOOLS
                  </div>
                  <div className="hidden sm:flex items-center gap-2 px-2.5 py-1 bg-accent/10 rounded text-xs font-medium text-accent-foreground">
                    <div className="w-1.5 h-1.5 rounded-full bg-accent"></div>
                    CERTIFIED DOMAIN RATING
                  </div>
                </div>
                {user ? (
                  <Link to="/admin">
                    <Button variant="ghost" className="text-xs">
                      Admin
                    </Button>
                  </Link>
                ) : (
                  <Link to="/auth">
                    <Button variant="ghost" className="text-xs">
                      Sign in
                    </Button>
                  </Link>
                )}
              </div>
            </div>
          </header>

          <section className="container mx-auto px-6 py-8">
            <h1 className="text-3xl font-bold text-foreground mb-1.5">
              The best tools, all in one place.
            </h1>
            <p className="text-sm text-muted-foreground mb-5">
              Find the best tools for you.
            </p>
            <Button className="bg-primary text-primary-foreground hover:bg-primary/90 text-sm px-4 py-2">
              <Plus className="h-4 w-4 mr-2" />
              Submit tool
            </Button>
          </section>

          <section className="container mx-auto px-4 sm:px-6 pb-12">
            {loading ? (
              <p>Loading tools...</p>
            ) : tools.length === 0 ? (
              <p className="text-muted-foreground">No tools found. Add some from the admin panel!</p>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-2.5">
                {tools.map((tool) => (
                  <Link key={tool.id} to={`/tool/${tool.id}`}>
                    <ToolCard
                      name={tool.name}
                      description={tool.description}
                      logo={tool.logo}
                      badge={tool.badge as "New" | "Deal" | undefined}
                    />
                  </Link>
                ))}
              </div>
            )}
          </section>
        </main>
      </div>
    </SidebarProvider>
  );
};

export default Index;
